# Generated by Django 4.1.6 on 2023-02-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='user',
            name='room',
            field=models.CharField(default=3, max_length=1000),
            preserve_default=False,
        ),
    ]
